### ISSUE TITLE
Lint Typescript templates

### ISSUE THREAD

**Issue by emclaug2** [brightlayer-ui/react-cli-templates#40]
#### Describe the bug
The typescript templates have a file that is preventing the cli from building without lint errors.

`reportWebVitals.ts` should be linted

#### What is the expected behavior?
New projects generated without lint errors.

#### Environment

		
Chrome windows

**Comment by joebochill** [comment]
@emclaug2 can you elaborate on what is happening here? The `reportWebVitals.ts` file has already disabled linting checks:
![image](https://user-images.githubusercontent.com/29152776/147660705-08f8c87d-0631-4c5b-9372-7f671d1e1451.png)

**Comment by jeffvg** [comment]
this works when you lint but does not work when you run it (yarn start)
