### ISSUE TITLE
Address Eslint/Typescript Compatibility Warning

### ISSUE THREAD

**Issue by emclaug2** [brightlayer-ui/react-cli-templates#48]
#### Describe the bug
Address this warning.

#### What is the expected behavior?
There should be no warning when attempting to lint a newly generated react projected via the BLUI CLI.

#### What are the steps to reproduce?
1. Generate a new project in react via CLI 
2. Run `yarn lint`

#### Screenshots or links to minimum reproduction example
```
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.5.0

YOUR TYPESCRIPT VERSION: 4.6.2

Please only submit bug reports when using the officially supported version.

```

#### Anything else to add?
No

**Comment by bkarambe** [comment]
Check whether this issue still exists after doing the dependency updates.
